### ISSUE TITLE
Potential re-working of motus package/Rbook chapter

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/MotusRBook#1]
- potentially remove some (or all?) of the functions from the motus R package and instead show them in the "exploring data" RBook chapter

**Comment by tabanid** [comment]
I had originally suggested this, but I think we are too far down that road. So we should just leave as is (at least for now). We should think carefully about the set of functions that we actually want in the package, and perhaps make a list of them somewhere (enhancements in issues).
