### ISSUE TITLE
Error in apply runs filter

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#10]
Error in rsqlite_send_query(conn@ptr, statement) : NOT NULL constraint failed: runsFilters.probability

I will push my changes to the book shortly. This occurs near the end, in the section around line 667. I'm almost certainly doing something silly, but I can't see what.

**Comment by tcrewe** [comment]
I've gotten this before when one of the probabilities in the df you are
trying to write to filter has NA probability.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tabanid** [comment]
yes, I didn't have that variable -- thanks
