### ISSUE TITLE
Login working intermittently

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#12]
"Please enter a value for login name at motus.org
==> 
ptaylor
Please enter a value for password at motus.org
==> 
tabanid
Error in value[[3L]](cond) : 
  The motus data server rejected your login credentials"

That happened after a long delay. 

Then it worked after I tried it later.

**Comment by denislepage** [comment]
There were some connections issues yesterday. We changed a setting and it seems to be working well again. I think there were other processes writing to the database at the same time, creating database locks. Something we'll need to keep an eye on.
