### ISSUE TITLE
Proposed new BI from Lotek

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#17]
Lotek has proposed a new set of burst intervals for tags, with the purpose of minimizing the numbers of ambiguous tags deployed. They want our 'tech people' to test these. 

One test is to generate test files with various (random) sets of tags, and run those through the entire data handling process. This would best be done on a separate implementation of the whole Motus server, to avoid conflicts with real tags. Such a test could also help us find issues with the current data processing.

**Comment by StuMackenzie** [comment]
See - https://github.com/MotusDev/Motus-TO-DO/issues/154
