### ISSUE TITLE
Errors with metadata function

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#18]
I called the metadata function ...

```
> metadata(ipsp.sql)
Loading complete Motus metadata
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbGetQuery’ for signature ‘"NULL", "character"’

```
I was already logged in to Motus.org, but thought I'd check than regardless ...

```
> ipsp.sql <- tagme(22, update= TRUE)
Checking for new data in project 22

```
Then called the metadata function again

```
> md.df <- metadata(ipsp.sql)
Loading complete Motus metadata
Done
> 
```
The returned value was NULL. 

My motus package (regular branch) appears to be up to date.
SHA1 (3239d683)

**Comment by tcrewe** [comment]
The text needs to be clarified for this. It apparently adds the metadata to
the recvDeps and tagDeps files, and doesn't create a df.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tabanid** [comment]
This behaviour is (now?) documented in section 3.4.8 in the book. (perhaps it always was).
