### ISSUE TITLE
motusTagID is not unique

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#20]
motusTagID can refer to multiple deployments. Check if this is made explicit in the book, and if not, fix it by always appending the tagDeployID as a suffix to the motusTagID, as a first step.

**Comment by tabanid** [comment]
We don't deal with this properly in the book. Presumably there should be a step that checks whether there are multiple deployments for a given motusTagID and then creates a unique tagID (by pasting deployID and motusTagID. This should be introduced into the workflow in chapter 4 (separate section around 4.3.3) and in chapter 5 (around 5.3.1).

**Comment by tcrewe** [comment]
I added some text to address this. Please feel free to check it out and comment; closing for now.
