### ISSUE TITLE
How to decide if we remove all runLen = 2

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/MotusRBook#23]
From a user:
"the R book does not describe how to identify "false negatives" with runLen = 2. I guess one has to decide from the context of each single case if one "trusts" detection data with runLen = 2?"

This is already in the book at the top of chapter 5, and then again in section 5.3.  I'm not sure where else we could put this, but it may be worth adding a line at the end of chapter 5 reminding people to go back and check runLen = 2 for potential true detections.  I don't think we need to script it out, but we do tell them to examine them later and then don't bring it up again.

**Comment by tcrewe** [comment]
I added a small section at the end. Please feel free to review, but closing this one for now.
