### ISSUE TITLE
No documentation for various filter functions

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#8]
?applyRunsFilter doesn't do anything

**Comment by tcrewe** [comment]
It does if you use the p.min statement?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tabanid** [comment]
Documentation seems to have been fixed (at least in the functions I've looked at).
