### ISSUE TITLE
running apply runs filter without being logged in results in an error

### ISSUE THREAD

**Issue by tabanid** [MotusWTS/MotusRBook#9]
I have been working on a session while not being logged in to Motus. When I tried to run apply runs filter, it returned an error. 

Error in (function (val)  : session variable 'userLogin' is undefined

**Comment by tcrewe** [comment]
The filters are attached to the user Login, so this might be why - if so,
there should be an error statement that you need to be logged in to apply a
filter?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tabanid** [comment]
Perhaps these are general issues surrounding the various filter functions (and related to other issues when first logging in or not being logged in). In any event it should be raised in MotusDev if it comes up again so I'll close it here.
